FROM almalinux:8
RUN yum install nginx
CMD [ "nginx","-g","demon off" ]
LABEL   Author="Shankar"\
            ENV=DEV\
                Project="Learn Devops"\
                    Duratio="120HRS"\
                        Version="Version_1"
EXPOSE 80/TCP